#!/usr/bin/env python3
"""
extract.py - Financial Audit Data Extraction & Processing Script
Directorate of Local Fund Audit — Government of Sikkim

Description:
    Reads raw financial audit datasets (.xlsx or .csv) from the data/ folder,
    cleans currency values, normalizes headers, calculates Closing Balances,
    and outputs formatted JSON or JS variable snippets for index.html.

Usage:
    python3 scripts/extract.py -i data/sample_audit.xlsx -o data/records.json
    python3 scripts/extract.py -i data/sample_audit.xlsx -o data/records.js --export-js
"""

import sys
import json
import argparse
from pathlib import Path

try:
    import pandas as pd
except ImportError:
    print("Error: pandas library is required. Install dependencies via: pip install -r requirements.txt")
    sys.exit(1)


def clean_currency_val(val):
    """Clean numeric inputs, stripping currency symbols (₹), commas, and whitespace."""
    if pd.isna(val) or val is None:
        return 0.0
    if isinstance(val, (int, float)):
        return float(val)
    
    cleaned_str = str(val).replace('₹', '').replace(',', '').strip()
    try:
        return float(cleaned_str)
    except ValueError:
        return 0.0


def extract_and_transform(input_filepath):
    """
    Reads an Excel or CSV file, maps headers, calculates Closing Balances,
    and returns clean structured dict records.
    """
    file_path = Path(input_filepath)

    if not file_path.exists():
        raise FileNotFoundError(f"Input file not found at: {input_filepath}")

    if file_path.suffix.lower() in ['.xlsx', '.xls']:
        df = pd.read_excel(file_path)
    elif file_path.suffix.lower() == '.csv':
        df = pd.read_csv(file_path)
    else:
        raise ValueError("Unsupported file format. Please provide a .xlsx or .csv file.")

    df.columns = [str(col).strip().lower() for col in df.columns]

    column_mapping = {
        'body': ['local body', 'local body name', 'body', 'name', 'municipality', 'panchayat'],
        'tier': ['tier', 'level', 'type', 'category'],
        'year': ['financial year', 'fy', 'year', 'period'],
        'ob': ['opening balance', 'opening bal', 'ob', 'opening_balance'],
        'receipts': ['receipts', 'receipt', 'income', 'total_receipts'],
        'payments': ['payments', 'payment', 'expenditure', 'total_payments']
    }

    mapped_cols = {}
    for target_key, synonyms in column_mapping.items():
        for col in df.columns:
            if col in synonyms:
                mapped_cols[target_key] = col
                break

    records = []
    for idx, row in df.iterrows():
        body_name = str(row.get(mapped_cols.get('body', ''), f"Local Body #{idx + 1}")).strip()
        tier_name = str(row.get(mapped_cols.get('tier', ''), "Urban Local Body")).strip()
        fy = str(row.get(mapped_cols.get('year', ''), "2024-25")).strip()

        ob_val = clean_currency_val(row.get(mapped_cols.get('ob', 0)))
        receipts_val = clean_currency_val(row.get(mapped_cols.get('receipts', 0)))
        payments_val = clean_currency_val(row.get(mapped_cols.get('payments', 0)))
        cb_val = ob_val + receipts_val - payments_val

        records.append({
            "id": idx + 1,
            "body": body_name,
            "tier": tier_name,
            "year": fy,
            "ob": round(ob_val, 2),
            "receipts": round(receipts_val, 2),
            "payments": round(payments_val, 2),
            "cb": round(cb_val, 2)
        })

    return records


def main():
    parser = argparse.ArgumentParser(description="Extract and process audit data for Sikkim LFA Dashboard.")
    parser.add_argument("-i", "--input", required=True, help="Path to input Excel (.xlsx) or CSV file in data/")
    parser.add_argument("-o", "--output", default="data/records.json", help="Path to output file")
    parser.add_argument("--export-js", action="store_true", help="Export as JS const variable for index.html")

    args = parser.parse_args()

    try:
        print(f"[*] Extracting audit data from: {args.input}")
        records = extract_and_transform(args.input)
        output_path = Path(args.output)
        output_path.parent.mkdir(parents=True, exist_ok=True)

        if args.export_js:
            js_content = f"// Auto-generated by scripts/extract.py\nconst allRecords = {json.dumps(records, indent=2)};\n"
            output_path.write_text(js_content, encoding="utf-8")
            print(f"[✓] Exported JavaScript data array to: {output_path}")
        else:
            with open(output_path, "w", encoding="utf-8") as f:
                json.dump(records, f, indent=2, ensure_ascii=False)
            print(f"[✓] Exported JSON records to: {output_path}")

        print(f"[i] Total records processed: {len(records)}")

    except Exception as e:
        print(f"[X] Extraction Error: {str(e)}")
        sys.exit(1)


if __name__ == "__main__":
    main()